#!/bin/bash
#Koostada skript "2016. aasta valiti Eesti presidendiks Kersti Kaljulaid"
#Määra muutujad 2016 arvuna ja Kersti Kaljulaid sõnana

aasta="2016."
lause_keskosa="aastal valiti Eesti presidendiks"
president="Kersti Kaljulaud"

echo "$aasta $lause_keskosa $president" 
 

